pipeline {
    agent any
    tools {
        maven 'Maven3'
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                dir('starter') {
                    sh 'mvn -B clean package'
                }
            }
        }
        stage('Test') {
            steps {
                dir('starter') {
                    sh 'mvn -B test'
                }
            }
            post {
                always {
                    dir('starter') {
                        junit 'target/surefire-reports/*.xml'
                    }
                }
            }
        }
        stage('Jacoco') {
            steps {
                jacoco(
                    execPattern: 'starter/target/jacoco.exec',
                    classPattern: 'starter/target/classes',
                    sourcePattern: 'starter/src/main/java',
                    exclusionPattern: '**/test/**'
                )
            }
            post {
                always {
                    dir('starter') {
                        archiveArtifacts artifacts: 'target/site/jacoco/**', fingerprint: true
                    }
                }
            }
        }
        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'starter/target/*.jar', fingerprint: true
            }
        }
    }
}